# DO NOT DELETE

algo_name: run_sister_workflow
version: dev
environment: ubuntu
repository_url: https://gitlab.com/geospec/cwl-pipeline-executor.git
docker_url: mas.dit.maap-project.org/root/maap-workspaces/base_images/vanilla:dit
# queue chosen when registering
queue: 15GB

# fill out these fields
# explain what this algorithm does
description: Sister Workflow

build_command: cwl-pipeline-executor/build-env.sh
# path to the wrapper script for running the algorithm
run_command: cwl-pipeline-executor/run-cwl.sh
# set a storage value in GB or MB or KB, e.g. "100GB", "20MB", "10KB"
disk_space: 10GB
inputs:
# remove below this line if no inputs
# rename and set algorithm input names accordingly
  - name: workflow_config
    type: config
