# DO NOT DELETE

algorithm_name: run_sister_workflow
algorithm_version: dev
repository_url: https://gitlab.com/geospec/cwl-pipeline-executor.git
docker_container_url: mas.dit.maap-project.org/root/maap-workspaces/base_images/vanilla:develop

# fill out these fields
# explain what this algorithm does
algorithm_description: Sister Workflow

build_command: cwl-pipeline-executor/build-env.sh
# path to the wrapper script for running the algorithm
run_command: cwl-pipeline-executor/run-cwl.sh
# set a storage value in GB or MB or KB, e.g. "100GB", "20MB", "10KB"
disk_space: 10GB
inputs:
# remove below this line if no inputs
# rename and set algorithm input names accordingly
  positional:
    - name: workflow_name
      default: "sister-workflow-conditional"
  config:
    - name: workflow_config
      type: object
      description: Workflow config

    - name: precondition_file
      type: string
      description: Precondition file to use
      default: "sister-router"
